start_date: '2026-06-04'
timezone: America/Denver
ntfy_base_url: https://ntfy.jade.rip
notify_time: 08:00
members:
- name: Jade
- name: Hannah
rooms:
- name: Kitchen
  tasks:
  - Wipe down counters & stovetop
  - Dishes
- name: Living Room
  tasks:
  - Vacuum
  - Dust surfaces
  - Tidy up
- name: Master Bedroom
  tasks:
  - Vacuum
  - Dust surfaces
- name: Own Office
  tasks:
  - Vacuum
  - Tidy desk
  - Empty trash
- name: Bathroom
  tasks:
  - Clean toilet
  - Vacuum
  - Clean Mirror
