start_date: '2026-06-04'
ntfy_base_url: https://ntfy.sh
notify_time: 08:00
members:
- name: Jade
  ntfy: jade
- name: Hannah
  ntfy: hannah
rooms:
- name: Kitchen
  tasks:
  - Dishes
  - Sweep & mop floor
  - Wipe down counters & stovetop
- name: Living Room
  tasks:
  - Vacuum
  - Dust surfaces
  - Tidy up
- name: Master Bedroom
  tasks:
  - Make bed
  - Vacuum
  - Dust surfaces
- name: Own Office
  tasks:
  - Vacuum
  - Tidy desk
  - Empty trash
- name: Bathroom
  tasks:
  - Clean toilet
